algoritmo "ficha"
// Função : nome, idade e salário de alguém
// Autor : agatha camille
// Data : 07/03/2022
// Seção de Declarações 
var
nome: caracter
idade: inteiro
salário: real

inicio
// Seção de Comandos
escreval ("Digite seu nome: ")
leia(nome)
escreval ("Digite sua idade: ")
leia(idade)
escreval ("Digite seu salário: ")
leia(salário)

escreval ("Seu nome é: ",nome)
escreval ("Sua idade é: ",idade)
escreval ("Seu salário é: ",salario)
fimalgoritmo
