algoritmo "exercicio2"
// Função :
// Autor : Agatha Camille
// Data : 02/05/2022
// Seção de Declarações 
var

n1,n2,n3,n4,total:real

inicio
// Seção de Comandos 

escreval("Digite o primeiro número: ")
leia(n1)
escreval("Digite o segundo número: ")
leia(n2)
escreval("Digite o terceiro número: ")
leia(n3)
escreval("Digite o quarto número: ")
leia(n4)
total<-(n1*n1)+(n2*n2)+(n3*n3)+(n4*n4)
escreval("A soma do quadrado desses números é: ",total)


fimalgoritmo
