algoritmo "ConverterDolar"
// Função : Converter real em dólar
// Autor : Agatha Camille
// Data : 02/05/2022
// Seção de Declarações 
var

reais,cotacao,dolar:real


inicio
// Seção de Comandos 

escreval("Digite o valor em reais da cotação atual do dólar: ")
leia(cotacao)
escreval("digite a quantia em reais que será convertido em dóalr: ")
leia(reais)
dolar<-reais/cotacao
escreval("O valor convertido equivale a U$",dolar)




fimalgoritmo
