algoritmo "exercicio3"
// Função :
// Autor : Agatha Camille
// Data : 03/05/2022
// Seção de Declarações 
var

peca,qtde,comissao:real


inicio
// Seção de Comandos 

escreval("Digite o valor unitário da peça: ")
leia(peca)
escreval("Digite a quantidade de peças vendidas: ")
leia(qtde)
comissao<-qtde*0.05
escreval("A comissão que o vendedor deverá receber será de R$",comissao)



fimalgoritmo
